/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Prueba;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;



/**
 *
 * @author user
 */

public class Pcollection extends javax.swing.JFrame {
    private List<JTextField> Textos;
    
     //private List<JButton> Botones;
     //private int indice;
    /**
     * Creates new form Pcollection
     */
    public Pcollection() {
        initComponents();
        //Botones= new ArrayList<>();
        Textos=new ArrayList<>();
        //indice=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pane1 = new javax.swing.JPanel();
        BttImprimir = new javax.swing.JButton();
        BttEliminar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar48.png"))); // NOI18N
        BtAgregar.setText("Agregar");
        BtAgregar.setBorderPainted(false);
        BtAgregar.setContentAreaFilled(false);
        BtAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar64.png"))); // NOI18N
        BtAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar64.png"))); // NOI18N
        BtAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAgregarActionPerformed(evt);
            }
        });

        Pane.setForeground(new java.awt.Color(204, 255, 255));
        Pane.setLayout(new java.awt.GridLayout(3, 0));

        Pane1.setForeground(new java.awt.Color(204, 204, 255));
        Pane1.setLayout(new java.awt.GridLayout(3, 0));
        jScrollPane2.setViewportView(Pane1);

        Pane.add(jScrollPane2);

        jScrollPane1.setViewportView(Pane);

        BttImprimir.setBackground(new java.awt.Color(242, 242, 242));
        BttImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imprimir64.png"))); // NOI18N
        BttImprimir.setText("Imprimir");
        BttImprimir.setBorderPainted(false);
        BttImprimir.setContentAreaFilled(false);
        BttImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BttImprimir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imprimir48.png"))); // NOI18N
        BttImprimir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imprimir48.png"))); // NOI18N
        BttImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BttImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttImprimirActionPerformed(evt);
            }
        });

        BttEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar48.png"))); // NOI18N
        BttEliminar.setText("Eliminar");
        BttEliminar.setBorderPainted(false);
        BttEliminar.setContentAreaFilled(false);
        BttEliminar.setDisabledIcon(null);
        BttEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BttEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar64.png"))); // NOI18N
        BttEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar48.png"))); // NOI18N
        BttEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BttEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(BttImprimir)
                        .addGap(28, 28, 28)
                        .addComponent(BttEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BttEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BttImprimir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAgregarActionPerformed
        // TODO add your handling code here:
        JTextField Texto =new JTextField();//"Texto"+indice para agregar nombre a los botones o t
        Pane.add(Texto);
        Textos.add(Texto);
        //indice++;
        Pane.updateUI();
    }//GEN-LAST:event_BtAgregarActionPerformed

    private void BttImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttImprimirActionPerformed
        // TODO add your handling code here:
        for (JTextField Texto : Textos) {
            //JOptionPane.showMessageDialog(rootPane,Texto.getText() );
            System.out.println(Texto.getText());
        }
    }//GEN-LAST:event_BttImprimirActionPerformed

    private void BttEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttEliminarActionPerformed
        // TODO add your handling code here:
        int tex = Textos.size() - 1;//devuelve la catidad de los elementos restando uno 
           if (tex >= 0) {//compara si hay almenos un elemento antes de eleminar
            JTextField texteliminar = Textos.get(tex);
            Pane.remove(texteliminar);//elimina el componente del contenedor del panel
            Textos.remove(tex);//elimina el elemento de la lista de textos
            Pane.updateUI();//actualiza la interfaz de usuario para mostrar los cambios
            } 
    }//GEN-LAST:event_BttEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pcollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pcollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pcollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pcollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pcollection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAgregar;
    private javax.swing.JButton BttEliminar;
    private javax.swing.JButton BttImprimir;
    private javax.swing.JPanel Pane;
    private javax.swing.JPanel Pane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
